version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Kilo2022*
      MYSQL_USER: danidevcu
      MYSQL_PASSWORD: Kilo2022*
      MYSQL_DATABASE: notetaking
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
